# ~/.config/starship.toml

add_newline = true

# Main prompt format (using valid syntax for Starship)
format = """\
($username) on ($hostname) in $directory > \
"""

# Right side format (just the duration)
right_format = """$cmd_duration"""

# Username
[username]
show_always = true
style_user = "bold cyan"
format = "([$user]($style))"

# Hostname
[hostname]
ssh_only = false
style = "bold yellow"
format = "([$hostname]($style))"

# Directory
[directory]
style = "bold blue"
format = "[$path]($style)"

# Command duration
[cmd_duration]
min_time = 0
show_milliseconds = false
format = "⏱ $duration"
style = "bold white"

# Disable the prompt character (since you're customizing the prompt)
[character]
disabled = true

